services:
  fastapi-hotmart-challenge:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  streamlit-hotmart-challenge:
    build:
      context: .
      dockerfile: src/streamlit/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    env_file:
      - .env

  qdrant-hotmart-challenge:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: