services:
  fastapi-hotmart-challenge:
    build:
      context: .
      dockerfile: Dockerfile_API
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
  streamlit-hotmart-challenge:
    build:
      context: .
      dockerfile: Dockerfile_Streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    env_file:
      - .env