cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    teste:
      email: teste@teste.com
      failed_login_attempts: 0
      logged_in: false
      name: "Usuário Teste"
      password: $2b$12$OrFlkJ9tI47XzfGHp4kZHOSUAq11CcIv48n6tKu22YRVPyf.hgmP.
pre-authorized:
  emails:
  - teste@teste.com
