cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    test:
      email: test@test.com
      failed_login_attempts: 0
      logged_in: false
      name: Test User
      password: $2b$12$043Bk4dtLlVqj0JjIeNtye1XYZteFENNij70fc7ZwRCUrdoQErCh6
pre-authorized:
  emails:
  - test@test.com
